server:
  port: 8080

endpoints:
  shutdown:
    sensitive: false
    enabled: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pse
    username: postgres
    password: postgres
    max-active: 10
    initial-size: 5
    max-idle: 5
    min-idle: 1
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 15000
    min-evictable-idle-time-millis: 60000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate.ddl-auto: update

logging:
  level:
    com.pse: DEBUG

phisix:
  url: http://phisix-api.appspot.com/stocks

pse-edge:
  url: http://edge.pse.com.ph/companyPage/financial_reports_view.do?cmpy_id=